export const AUTHENTICATE = 'AUTHENTICATE';

export const RECOVER_CODE_REQUEST = 'RECOVER_CODE_REQUEST';
export const RECOVERY_CODE_SUCCESS = 'RECOVERY_CODE_SUCCESS';
export const RECOVERY_CODE_FAIL = 'RECOVERY_CODE_FAIL';
export const RECOVERY_CODE_RESET = 'RECOVERY_CODE_RESET';

export const VALIDATE_CODE_REQUEST = 'VALIDATE_CODE_REQUEST';
export const VALIDATE_CODE_SUCCESS = 'VALIDATE_CODE_SUCCESS';
export const VALIDATE_CODE_FAIL = 'VALIDATE_CODE_FAIL';
export const VALIDATE_CODE_RESET = 'VALIDATE_CODE_RESET';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_RESET = 'CHANGE_PASSWORD_RESET';
